// schema.dbml
Table users {
  id         int       [pk, increment]
  email      varchar   [unique, note: "Google e-mail"]
  name       varchar
  role       varchar   [default: "student"]
}

Table events {
  id         int       [pk, increment]
  title      varchar
  event_date datetime
  created_at datetime   [default: `now()`]
  author_id  int        [ref: > users.id]
  is_deleted bool       [default: false]
}

Table votes {
  user_id   int [ref: > users.id]
  event_id  int [ref: > events.id]
  value     int // +1 or -1
  note: "PK = (user_id, event_id)"
  indexes {
    (user_id, event_id) [pk]
  }
}

Table comments {
  id        int [pk, increment]
  body      text
  created_at datetime [default: `now()`]
  user_id   int [ref: > users.id]
  event_id  int [ref: > events.id]
}
